### ISSUE TITLE
How to run specs?

### ISSUE THREAD

**Issue by kfatehi** [sergzak022/scrape-smc#1]
I see there is a spec folder with tests in it but you have not defined `npm test` so it is unclear how to execute them... The stars have to align for me to infer the right tooling, such as mocha & chai or lab & code, etc... lots of choices. Please update this with the correct way to invoke your specs https://github.com/sergzak022/scrape-smc/blob/master/package.json#L7

**Comment by sergzak022** [comment]
Thnks, just updated it
